server:
  port: 8286
spring:
  application:
    name: careld-vision-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/careld_vision?useUnicode=true&characterEncoding=utf-8&useSSL=${MYSQL_USE_SSL:false}&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: ${JWT_SECRET}
